export const
  AMBITS = {
    LAND: 'LAND',
    SKY: 'SKY',
    SPACE: 'SPACE',
    WATER: 'WATER',
  },

  COMMAND_STRUCT_DEFAULTS = {
    COUNTER_ATTACK_DAMAGE: 2,
    MAX_HEALTH: 6
  },

  DEFENSE_COMPONENT_TYPES = {
    AFTERMARKET_ENGINE: 'AFTERMARKET_ENGINE',
    AMBIT_DEFENSE: 'AMBIT_DEFENSE',
    ARMOUR: 'ARMOUR',
    COUNTER_MEASURE: 'COUNTER_MEASURE',
    DEFAULT: 'DEFAULT',
    EVADE_COUNTER_ATTACK: 'EVADE_COUNTER_ATTACK',
  },

  DEFENSE_COMPONENTS = {
    ARMOUR: 'ARMOUR',
    DEFENSIVE_MANEUVER: 'DEFENSIVE MANEUVER',
    INDIRECT_COMBAT_MODULE: 'INDIRECT COMBAT MODULE',
    OMNI_ENGINE: 'OMNI_ENGINE',
    SIGNAL_JAMMING: 'SIGNAL JAMMING',
    STEALTH_MODE: 'STEALTH_MODE',
  },

  FLEET_STRUCT_DEFAULTS = {
    ARMOUR: 0,
    ATTACK_DAMAGE: 2,
    COUNTER_ATTACK_DAMAGE: 1,
    MAX_HEALTH: 3,
  },

  MANUAL_WEAPONS = {
    ATTACK_RUN: 'ATTACK RUN',
    GUIDED_WEAPONRY: 'GUIDED WEAPONRY',
    SELF_DESTRUCT: 'SELF DESTRUCT',
    UNGUIDED_WEAPONRY: 'UNGUIDED WEAPONRY',
  },

  MANUAL_WEAPON_SLOTS = {
    PRIMARY: 'PRIMARY',
    SECONDARY: 'SECONDARY'
  },

  ORDER_OF_AMBITS = [
    AMBITS.WATER,
    AMBITS.LAND,
    AMBITS.SKY,
    AMBITS.SPACE
  ],

  PASSIVE_WEAPONS = {
    ADVANCED_COUNTER_ATTACK: 'ADVANCED COUNTER ATTACK',
    COUNTER_ATTACK: 'COUNTER ATTACK',
    LAST_RESORT: 'LAST RESORT',
    STRONG_COUNTER_ATTACK: 'STRONG COUNTER ATTACK'
  },

  UNIT_TYPES = {
    ARTILLERY: 'ARTILLERY',
    COMMAND_SHIP: 'COMMAND_SHIP',
    CRUISER: 'CRUISER',
    DESTROYER: 'DESTROYER',
    FIGHTER_JET: 'FIGHTER JET',
    GALACTIC_BATTLESHIP: 'GALACTIC BATTLESHIP',
    HIGH_ALTITUDE_INTERCEPTOR: 'HIGH ALTITUDE INTERCEPTOR',
    SAM_LAUNCHER: 'SAM LAUNCHER',
    SPACE_FRIGATE: 'SPACE FRIGATE',
    STAR_FIGHTER: 'STAR FIGHTER',
    STEALTH_BOMBER: 'STEALTH_BOMBER',
    SUB: 'SUB',
    TANK: 'TANK'
  }
;
